networks:
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  n8n:
    environment:
      GENERIC_TIMEZONE: "${TZ:?err}"
      N8N_LISTEN_ADDRESS: "0.0.0.0"
      N8N_METRICS: true
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${N8N_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${N8N_VIRTUAL_PORT:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "90s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"
      timeout: "10s"
    image: "n8nio/n8n:${N8N_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.n8n.entrypoints: "websecure"
      traefik.http.routers.n8n.rule: "Host(`${N8N_VIRTUAL_HOST:?err}`)"
      traefik.http.routers.n8n.tls: true
      traefik.http.services.n8n.loadbalancer.server.port: "${N8N_VIRTUAL_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "n8n-data:/home/node/.n8n"
volumes:
  n8n-data: null
