# yaml-language-server: $schema=../../schemas/service.schema.json
name: n8n
description: "n8n is a workflow automation platform that gives technical teams the flexibility of code with the speed of no-code"
url: "https://n8n.io/"
local_url: "https://n8n.services.local"
docker_hub_url: "https://hub.docker.com/r/n8nio/n8n"
dockerfile_url: "https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/Dockerfile"

homepage:
  - name: n8n
    container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-n8n-1"
    description: "Fair-code workflow automation platform with native AI capabilities"
    href: "https://{{HOMEPAGE_VAR_N8N_HOSTNAME}}/"
    icon: "sh-n8n.png"
    server: "my-docker"
    showStats: true
