networks:
  nginx-proxy:
    external: true
    name: "${NGINX_PROXY_NETWORK:?err}"
services:
  it-tools:
    environment:
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${IT_TOOLS_VIRTUAL_HOST:?err}"
    image: "corentinth/it-tools:${IT_TOOLS_VERSION:?err}"
    labels:
      wud.tag.include: "latest"
      wud.watch.digest: true
    networks:
      - "nginx-proxy"
    restart: "unless-stopped"
