networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  it-tools:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://127.0.0.1 || exit 1"
      timeout: "10s"
    image: "corentinth/it-tools:${IT_TOOLS_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.it-tools.entrypoints: "websecure"
      traefik.http.routers.it-tools.middlewares: "authentik-server@docker"
      traefik.http.routers.it-tools.rule: "Host(`${IT_TOOLS_HOSTNAME:?err}`)"
      traefik.http.routers.it-tools.tls: true
      traefik.http.services.it-tools.loadbalancer.server.port: "${IT_TOOLS_HOSTNAME_PORT:?err}"
      wud.tag.include: "latest"
      wud.watch: true
      wud.watch.digest: true
    networks:
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
