networks:
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  whatsupdocker:
    environment:
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${WHATSUPDOCKER_VIRTUAL_HOST:?err}"
      WUD_REGISTRY_CUSTOM_OSGEO_URL: "${WHATSUPDOCKER_WUD_REGISTRY_CUSTOM_OSGEO_URL}"
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "curl --fail --silent --show-error http://localhost:3000/api/containers || exit 1"
      timeout: "10s"
    image: "getwud/wud:${WHATSUPDOCKER_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.whatsupdocker.entrypoints: "websecure"
      traefik.http.routers.whatsupdocker.middlewares: "authentik-server@docker"
      traefik.http.routers.whatsupdocker.rule: "Host(`${WHATSUPDOCKER_VIRTUAL_HOST:?err}`)"
      traefik.http.routers.whatsupdocker.tls: true
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "whatsupdocker-data:/store"
volumes:
  whatsupdocker-data: null
