profiles:
  default:
    mongo: 10
    mysql: 10
    postgres: 10
    authentik: 20
    traefik: 30
    cadvisor:
    dozzle:
    grafana:
    homepage:
    it-tools:
    mailpit:
    n8n:
    ntfy:
    ollama:
    omni-tools:
    prometheus:
    rabbitmq:
    redis:
    seaweedfs:
    whatsupdocker:
  testing:
    postgres: 10
    authentik: 20
    traefik: 30
    homepage:
    ntfy:
    whatsupdocker:
  work:
    mongo: 10
    mysql: 10
    postgres: 10
    authentik: 20
    traefik: 30
    homepage:
    it-tools:
    mailpit:
    omni-tools:
    rabbitmq:
    redis:
    seaweedfs:
