#!/bin/bash
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "
  CREATE USER IF NOT EXISTS '${MYSQL_EXPORTER_USER}'@'%'
  IDENTIFIED BY '${MYSQL_EXPORTER_USER_PASSWORD}'
  WITH MAX_USER_CONNECTIONS 3;
  
  GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '${MYSQL_EXPORTER_USER}'@'%';

  FLUSH PRIVILEGES;
"
