#!/bin/bash

set -eu

MYSQL_ROOT_PASSWORD=$(cat /run/secrets/MYSQL_ROOT_PASSWORD)

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE USER IF NOT EXISTS '${MYSQL_SERVICES_USER}'@'%' IDENTIFIED WITH caching_sha2_password BY '$(cat /run/secrets/MYSQL_SERVICES_USER_PASSWORRD)' WITH MAX_USER_CONNECTIONS 3;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP,
PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES,
CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE,
EVENT, TRIGGER
ON *.* TO '${MYSQL_SERVICES_USER}'@'%';
EOSQL
