networks:
  mongo:
    external: true
    name: "${MONGO_NETWORK:?err}"
  nginx-proxy:
    external: true
    name: "${NGINX_PROXY_NETWORK:?err}"
services:
  mongo:
    command: "mongod --auth --replSet rs0 --bind_ip_all --keyFile=/data/keyfile"
    environment:
      GLIBC_TUNABLES: "${MONGO_GLIBC_TUNABLES}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
      MONGO_PROFILE: "${MONGO_PROFILE}"
      TZ: "${TZ:?err}"
    image: "mongo:${MONGO_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "mongo"
    restart: "unless-stopped"
    ulimits:
      nofile:
        hard: 64000
        soft: 64000
      nproc:
        hard: 64000
        soft: 64000
    volumes:
      - "${PWD}/services/mongo/backups:/data/backups:ro"
      - "${PWD}/services/mongo/keyfile:/data/keyfile:ro"
      - "mongo-config:/data/configdb"
      - "mongo-data:/data/db"
  mongo-mongo-express:
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_ME_CONFIG_BASICAUTH_PASSWORD:?err}"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_ME_CONFIG_BASICAUTH_USERNAME:?err}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_OPTIONS_EDITORTHEME: "${MONGO_ME_CONFIG_OPTIONS_EDITORTHEME}"
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${MONGO_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${MONGO_VIRTUAL_PORT:?err}"
    image: "mongo-express:${MONGO_ME_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "mongo"
      - "nginx-proxy"
    restart: "unless-stopped"
volumes:
  mongo-config: null
  mongo-data: null
