networks:
  mongo:
    external: true
    name: "${MONGO_NETWORK:?err}"
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  mongo:
    command: "mongod --auth --replSet rs0 --bind_ip_all --keyFile=/data/keyfile"
    environment:
      GLIBC_TUNABLES: "${MONGO_GLIBC_TUNABLES}"
      MONGO_EXPORTER_USER: "${MONGO_EXPORTER_USER:?err}"
      MONGO_EXPORTER_USER_PASSWORD: "${MONGO_EXPORTER_USER_PASSWORD:?err}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
      MONGO_PROFILE: "${MONGO_PROFILE}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"
      timeout: "10s"
    image: "mongo:${MONGO_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mongo"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    ulimits:
      nofile:
        hard: 64000
        soft: 64000
      nproc:
        hard: 64000
        soft: 64000
    volumes:
      - "${PWD}/services/mongo/backups:/data/backups:ro"
      - "${PWD}/services/mongo/initdb:/docker-entrypoint-initdb.d:ro"
      - "${PWD}/services/mongo/keyfile:/data/keyfile:ro"
      - "mongo-config:/data/configdb"
      - "mongo-data:/data/db"
  mongo-mongo-express:
    depends_on:
      mongo:
        condition: "service_healthy"
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_OPTIONS_EDITORTHEME: "${MONGO_EXPRESS_ME_CONFIG_OPTIONS_EDITORTHEME}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://127.0.0.1:8081 || exit 1"
      timeout: "10s"
    image: "mongo-express:${MONGO_EXPRESS_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.mongo-mongo-express.entrypoints: "websecure"
      traefik.http.routers.mongo-mongo-express.middlewares: "authentik-server@docker"
      traefik.http.routers.mongo-mongo-express.rule: "Host(`${MONGO_EXPRESS_HOSTNAME:?err}`)"
      traefik.http.routers.mongo-mongo-express.tls: true
      traefik.http.services.mongo-mongo-express.loadbalancer.server.port: "${MONGO_EXPRESS_HOSTNAME_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mongo"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
  mongo-prometheus-exporter:
    command:
      - "--mongodb.uri=mongodb://mongo:27017"
    depends_on:
      mongo:
        condition: "service_healthy"
    environment:
      MONGODB_PASSWORD: "${MONGO_EXPORTER_USER_PASSWORD:?err}"
      MONGODB_USER: "${MONGO_EXPORTER_USER:?err}"
    image: "percona/mongodb_exporter:${MONGO_PROMETHEUS_EXPORTER_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mongo"
      - "prometheus"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
volumes:
  mongo-config: null
  mongo-data: null
