networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
  rabbitmq:
    external: true
    name: "${RABBITMQ_NETWORK:?err}"
services:
  rabbitmq:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"
    environment:
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:?err}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "rabbitmq-diagnostics -q ping || exit 1"
      timeout: "10s"
    hostname: "rabbitmq-dev"
    image: "rabbitmq:${RABBITMQ_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.rabbitmq.entrypoints: "websecure"
      traefik.http.routers.rabbitmq.rule: "Host(`${RABBITMQ_HOSTNAME:?err}`)"
      traefik.http.routers.rabbitmq.tls: true
      traefik.http.services.rabbitmq.loadbalancer.server.port: "${RABBITMQ_HOSTNAME_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+-management-alpine$$"
      wud.watch: true
    networks:
      - "proxy"
      - "rabbitmq"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
volumes:
  rabbitmq-data: null
