networks:
  mysql:
    external: true
    name: "${MYSQL_NETWORK:?err}"
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  mysql:
    environment:
      MYSQL_EXPORTER_USER: "${MYSQL_EXPORTER_USER:?err}"
      MYSQL_EXPORTER_USER_PASSWORD: "${MYSQL_EXPORTER_USER_PASSWORD:?err}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1"
      timeout: "10s"
    image: "mysql:${MYSQL_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mysql"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    ulimits:
      nofile:
        hard: 102400
        soft: 102400
      nproc:
        hard: 10240
        soft: 10240
    volumes:
      - "${PWD}/services/mysql/initdb:/docker-entrypoint-initdb.d:ro"
      - "mysql-data:/var/lib/mysql"
  mysql-phpmyadmin:
    depends_on:
      mysql:
        condition: "service_healthy"
    environment:
      PMA_HOSTS: "mysql"
      UPLOAD_LIMIT: "${MYSQL_PHPMYADMIN_UPLOAD_LIMIT}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "curl --fail --silent --show-error http://localhost/robots.txt || exit 1"
      timeout: "10s"
    image: "phpmyadmin:${MYSQL_PHPMYADMIN_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.mysql-phpmyadmin.entrypoints: "websecure"
      traefik.http.routers.mysql-phpmyadmin.middlewares: "authentik-server@docker"
      traefik.http.routers.mysql-phpmyadmin.rule: "Host(`${MYSQL_PHPMYADMIN_HOST:?err}`)"
      traefik.http.routers.mysql-phpmyadmin.tls: true
      traefik.http.services.mysql-phpmyadmin.loadbalancer.server.port: "${MYSQL_PHPMYADMIN_HOST_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mysql"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "${PWD}/services/mysql/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro"
  mysql-prometheus-exporter:
    command:
      - "--mysqld.address=mysql:3306"
      - "--mysqld.username=${MYSQL_EXPORTER_USER}"
    depends_on:
      mysql:
        condition: "service_healthy"
    environment:
      MYSQLD_EXPORTER_PASSWORD: "${MYSQL_EXPORTER_USER_PASSWORD:?err}"
      MYSQL_EXPORTER_USER: "${MYSQL_EXPORTER_USER:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://localhost:9104/metrics || exit 1"
      timeout: "10s"
    image: "prom/mysqld-exporter:${MYSQL_PROMETHEUS_EXPORTER_VERSION:?err}"
    labels:
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mysql"
      - "prometheus"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
volumes:
  mysql-data: null
