# yaml-language-server: $schema=../../schemas/service.schema.json
name: MySQL
description: "MySQL is the world's most popular open source database"
url: "https://www.mysql.com"
local_url: null
docker_hub_url: "https://hub.docker.com/_/mysql"
dockerfile_url: "https://github.com/docker-library/mysql/blob/master/innovation/Dockerfile.oracle"
dependents:
  - name: phpMyAdmin
    description: A web interface for MySQL and MariaDB
    url: "https://www.phpmyadmin.net"
    local_url: "https://phpmyadmin.services.local"
    docker_hub_url: "https://hub.docker.com/_/phpmyadmin"
    dockerfile_url: "https://github.com/phpmyadmin/docker/blob/master/apache/Dockerfile"
  - name: MySQL Server Exporter
    description: A Exporter for MySQL server metrics
    url: "https://github.com/prometheus/mysqld_exporter"
    local_url: null
    docker_hub_url: "https://hub.docker.com/r/prom/mysqld-exporter"
    dockerfile_url: "https://github.com/prometheus/mysqld_exporter/blob/main/Dockerfile"

homepage:
  - name: phpMyAdmin
    container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-mysql-phpmyadmin-1"
    description: "phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web"
    href: "https://{{HOMEPAGE_VAR_PHPMYADMIN_HOSTNAME}}/"
    icon: "/icons/phpmyadmin.ico"
    server: "my-docker"
    showStats: true
