networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  omni-tools:
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "curl --fail --silent --show-error http://127.0.0.1 || exit 1"
      timeout: "10s"
    image: "iib0011/omni-tools:${OMNI_TOOLS_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.omni-tools.entrypoints: "websecure"
      traefik.http.routers.omni-tools.middlewares: "authentik-server@docker"
      traefik.http.routers.omni-tools.rule: "Host(`${OMNI_TOOLS_HOSTNAME:?err}`)"
      traefik.http.routers.omni-tools.tls: true
      traefik.http.services.omni-tools.loadbalancer.server.port: "${OMNI_TOOLS_HOSTNAME_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
