networks:
  nginx-proxy:
    external: true
    name: "${NGINX_PROXY_NETWORK:?err}"
services:
  omni-tools:
    environment:
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${OMNI_TOOLS_VIRTUAL_HOST:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test: "curl --fail http://localhost || exit 1"
      timeout: "10s"
    image: "iib0011/omni-tools:${OMNI_TOOLS_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "nginx-proxy"
    restart: "unless-stopped"
