networks:
  healthchecks:
    external: true
    name: "${HEALTHCHECKS_NETWORK:?err}"
  nginx-proxy:
    external: true
    name: "${NGINX_PROXY_NETWORK:?err}"
services:
  healthchecks:
    command: "bash -c 'while !</dev/tcp/healthchecks-postgres/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'"
    environment:
      DB: "postgres"
      DB_HOST: "healthchecks-postgres"
      DB_NAME: "${HEALTHCHECKS_POSTGRES_DB:?err}"
      DB_PASSWORD: "${HEALTHCHECKS_POSTGRES_PASSWORD:?err}"
      DB_USER: "${HEALTHCHECKS_POSTGRES_USER:?err}"
      DEBUG: "${HEALTHCHECKS_DEBUG}"
      SECRET_KEY: "${HEALTHCHECKS_SECRET_KEY:?err}"
      SITE_ROOT: "https://${HEALTHCHECKS_VIRTUAL_HOST:?err}:${HEALTHCHECKS_VIRTUAL_PORT:?err}"
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${HEALTHCHECKS_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${HEALTHCHECKS_VIRTUAL_PORT:?err}"
    image: "healthchecks/healthchecks:${HEALTHCHECKS_VERSION:?err}"
    labels:
      wud.tag.include: "^v\\d+\\.\\d+$$"
    networks:
      - "healthchecks"
      - "nginx-proxy"
    restart: "unless-stopped"
    volumes:
      - "healthchecks-data:/data"
  healthchecks-postgres:
    environment:
      POSTGRES_DB: "${HEALTHCHECKS_POSTGRES_DB:?err}"
      POSTGRES_PASSWORD: "${HEALTHCHECKS_POSTGRES_PASSWORD:?err}"
      POSTGRES_USER: "${HEALTHCHECKS_POSTGRES_USER:?err}"
      TZ: "${TZ:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      timeout: "10s"
    image: "postgres:${HEALTHCHECKS_POSTGRES_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "healthchecks"
    restart: "unless-stopped"
    volumes:
      - "healthchecks-postgres-data:/var/lib/postgresql/data"
volumes:
  healthchecks-data: null
  healthchecks-postgres-data: null
