# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1

metadata:
  name: "domain-forward-auth-with-searched-flow"
  labels:
    purpose: "forward-auth-domain-level"

entries:
  - model: "authentik_providers_proxy.proxyprovider"
    identifiers:
      name: "traefik-forward-domain"
    state: "present"
    attrs:
      name: "Traefik Forward Auth (Domain)"
      access_token_validity: hours=24
      mode: "forward_domain"
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, default-provider-authorization-implicit-consent],
        ]
      authentication_url: "https://authentik.services.local"
      cookie_domain: "services.local"
      internal_host: "http://authentik-server:9000"
      external_host: "https://authentik.services.local"
      token_validity: "hours=24"
      intercept_header_auth: true
      internal_host_ssl_validation: false
      refresh_token_validity: "days=30"
      invalidation_flow:
        !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      redirect_uris:
        - matching_mode: "strict"
          url: "https://authentik.services.local/outpost.goauthentik.io/callback?X-authentik-auth-callback=true"
        - matching_mode: "strict"
          url: "https://authentik.services.local?X-authentik-auth-callback=true"
  - model: "authentik_core.application"
    state: "present"
    identifiers:
      name: "traefik-forward-domain-application"
    attrs:
      name: "Forward Auth"
      policy_engine_mode: "any"
      provider:
        !Find [
          authentik_providers_proxy.proxyprovider,
          [name, traefik-forward-domain],
        ]
      slug: "traefik-forward-auth"
    conditions: []
    permissions: []
  - identifiers:
      pk: !Find [authentik_outposts.outpost, [name, authentik Embedded Outpost]]
    model: authentik_outposts.outpost
    attrs:
      providers:
        [
          !Find [
            authentik_providers_proxy.proxyprovider,
            [name, traefik-forward-domain],
          ],
        ]
      config:
        authentik_host: "https://authentik.services.local"
