networks:
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  prometheus-blackbox-exporter:
    command:
      - "--config.file=/config/blackbox.yml"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "30s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://127.0.0.1:9115/health || exit 1"
      timeout: "10s"
    image: "prom/blackbox-exporter:${PROMETHEUS_BLACKBOX_EXPORTER_VERSION:?err}"
    labels:
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "${PWD}/services/prometheus/blackbox-exporter/blackbox.yml:/config/blackbox.yml:ro"
  prometheus-node-exporter:
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "30s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 -O /dev/null http://127.0.0.1:9100/metrics || exit 1"
      timeout: "30s"
    image: "prom/node-exporter:${PROMETHEUS_NODE_EXPORTER_VERSION:?err}"
    labels:
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "prometheus"
    pid: "host"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/:/host:ro,rslave"
  prometheus:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://127.0.0.1:9090/-/healthy || exit 1"
      timeout: "10s"
    image: "prom/prometheus:${PROMETHEUS_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.prometheus.entrypoints: "websecure"
      traefik.http.routers.prometheus.middlewares: "authentik-server@docker"
      traefik.http.routers.prometheus.rule: "Host(`${PROMETHEUS_HOSTNAME:?err}`)"
      traefik.http.routers.prometheus.tls: true
      traefik.http.services.prometheus.loadbalancer.server.port: "${PROMETHEUS_HOSTNAME_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "${PWD}/services/prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "prometheus-data:/prometheus"
volumes:
  prometheus-data: null
