global:
  scrape_interval: 15s

scrape_configs:
  - job_name: mysql
    metrics_path: /probe
    static_configs:
      - targets:
          - mysql:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysql-prometheus-exporter:9104

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongo-prometheus-exporter:9216"]
