networks:
  nginx-proxy:
    external: true
    name: "${NGINX_PROXY_NETWORK:?err}"
  owncloud:
    driver: "bridge"
    name: "${OWNCLOUD_NETWORK:?err}"
services:
  owncloud:
    environment:
      OWNCLOUD_ADMIN_PASSWORD: "${OWNCLOUD_ADMIN_PASSWORD:?err}"
      OWNCLOUD_ADMIN_USERNAME: "${OWNCLOUD_ADMIN_USERNAME:?err}"
      OWNCLOUD_DB_HOST: "${OWNCLOUD_DB_HOST:?err}"
      OWNCLOUD_DB_NAME: "${OWNCLOUD_DB_NAME:?err}"
      OWNCLOUD_DB_PASSWORD: "${OWNCLOUD_DB_PASSWORD:?err}"
      OWNCLOUD_DB_TYPE: "${OWNCLOUD_DB_TYPE:?err}"
      OWNCLOUD_DB_USERNAME: "${OWNCLOUD_DB_USERNAME:?err}"
      OWNCLOUD_DOMAIN: "${OWNCLOUD_DOMAIN:?err}"
      OWNCLOUD_MARIADB_UTF8MB4: "${OWNCLOUD_MARIADB_UTF8MB4}"
      OWNCLOUD_REDIS_ENABLED: "${OWNCLOUD_REDIS_ENABLED}"
      OWNCLOUD_REDIS_HOST: "${OWNCLOUD_REDIS_HOST:?err}"
      OWNCLOUD_TRUSTED_DOMAINS: "${OWNCLOUD_TRUSTED_DOMAINS:?err}"
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${OWNCLOUD_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${OWNCLOUD_VIRTUAL_PORT:?err}"
    image: "owncloud/server:${OWNCLOUD_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "nginx-proxy"
      - "owncloud"
    restart: "unless-stopped"
    volumes:
      - "owncloud-data:/mnt/data"
  owncloud-mariadb:
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    environment:
      MARIADB_AUTO_UPGRADE: "${OWNCLOUD_MARIADB_AUTO_UPGRADE}"
      MARIADB_DATABASE: "${OWNCLOUD_MARIADB_DATABASE:?err}"
      MARIADB_PASSWORD: "${OWNCLOUD_MARIADB_PASSWORD:?err}"
      MARIADB_ROOT_PASSWORD: "${OWNCLOUD_MARIADB_ROOT_PASSWORD:?err}"
      MARIADB_USER: "${OWNCLOUD_MARIADB_USER:?err}"
      TZ: "${TZ:?err}"
    image: "mariadb:${OWNCLOUD_MARIADB_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "owncloud"
    restart: "unless-stopped"
    volumes:
      - "owncloud-mariadb-data:/var/lib/mysql"
  owncloud-redis:
    command: ["--databases", "1"]
    environment:
      TZ: "${TZ:?err}"
    image: "redis:${OWNCLOUD_REDIS_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "owncloud"
    restart: "unless-stopped"
    volumes:
      - "owncloud-redis-data:/data"
volumes:
  owncloud-data: null
  owncloud-mariadb-data: null
  owncloud-redis-data: null
