# yaml-language-server: $schema=../../schemas/service.schema.json
name: SeaweedFS
description: "Enterprise-Grade Distributed Storage with Self-Healing"
url: "https://seaweedfs.com/"
local_url: "https://seaweedfs.services.local"
docker_hub_url: "https://hub.docker.com/r/corentinth/it-tools"
dockerfile_url: "https://github.com/seaweedfs/seaweedfs/blob/master/docker/Dockerfile.local"

homepage:
  - name: seaweedFS
    container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-seaweedfs-1"
    description: "Enterprise-Grade Distributed Storage with Self-Healing"
    href: "https://{{HOMEPAGE_VAR_SEAWEEDFS_HOSTNAME}}/"
    icon: "sh-seaweedfs.png"
    server: "my-docker"
    showStats: true
