networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  cadvisor:
    command:
      - "--housekeeping_interval=30s"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "512M"
    devices:
      - "/dev/kmsg"
    image: "ghcr.io/google/cadvisor:${CADVISOR_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.cadvisor.entrypoints: "websecure"
      traefik.http.routers.cadvisor.middlewares: "authentik-server@docker"
      traefik.http.routers.cadvisor.rule: "Host(`${CADVISOR_HOSTNAME:?err}`)"
      traefik.http.routers.cadvisor.tls: true
      traefik.http.services.cadvisor.loadbalancer.server.port: "${CADVISOR_HOSTNAME_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "proxy"
    privileged: true
    restart: "unless-stopped"
    volumes:
      - "/:/rootfs:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/var/run:/var/run:ro"
