networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  cadvisor:
    devices:
      - "/dev/kmsg"
    environment:
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${CADVISOR_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${CADVISOR_VIRTUAL_PORT:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1"
      timeout: "10s"
    image: "gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.cadvisor.entrypoints: "websecure"
      traefik.http.routers.cadvisor.middlewares: "authentik-server@docker"
      traefik.http.routers.cadvisor.rule: "Host(`${CADVISOR_VIRTUAL_HOST:?err}`)"
      traefik.http.routers.cadvisor.tls: true
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "proxy"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/:/rootfs:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/var/run:/var/run:ro"
