# yaml-language-server: $schema=../../schemas/service.schema.json
name: cAdvisor
description: Analyzes resource usage and performance characteristics of running containers
url: "https://github.com/google/cadvisor"
local_url: "https://cadvisor.services.local"
docker_hub_url: "https://github.com/google/cadvisor/pkgs/container/cadvisor"
dockerfile_url: "https://github.com/google/cadvisor/blob/master/deploy/Dockerfile"

homepage:
  - name: cAdvisor
    container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-cadvisor-1"
    description: "Analyzes resource usage and performance characteristics of running containers"
    href: "https://{{HOMEPAGE_VAR_CADVISOR_HOSTNAME}}/"
    icon: "sh-cadvisor.png"
    server: "my-docker"
    showStats: true
