networks:
  minio:
    external: true
    name: "${MINIO_NETWORK:?err}"
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  minio:
    command: "server /data --console-address ':9001'"
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:?err}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:?err}"
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${MINIO_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${MINIO_VIRTUAL_PORT:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "mc ready local || exit 1"
      timeout: "10s"
    image: "minio/minio:${MINIO_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.minio.entrypoints: "websecure"
      traefik.http.routers.minio.rule: "Host(`${MINIO_VIRTUAL_HOST:?err}`)"
      traefik.http.routers.minio.tls: true
      traefik.http.services.minio.loadbalancer.server.port: "${MINIO_VIRTUAL_PORT:?err}"
      wud.tag.include: "^RELEASE\\.\\d+-\\d+-\\d+T\\d+-\\d+-\\d+Z$$"
      wud.watch: true
    networks:
      - "minio"
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    volumes:
      - "minio-data:/data"
volumes:
  minio-data: null
