- Services:
    - authentik:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-traefik-1"
        description: "The authentication glue you need"
        href: "https://{{HOMEPAGE_VAR_AUTHENTIK_HOSTNAME}}/"
        icon: "sh-authentik.png"
        server: "my-docker"
        showStats: true
        widget:
          type: "authentik"
          key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
          url: "http://authentik-server:{{HOMEPAGE_VAR_AUTHENTIK_PORT}}"
    - cAdvisor:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-cadvisor-1"
        description: "Analyzes resource usage and performance characteristics of running containers"
        href: "https://{{HOMEPAGE_VAR_CADVISOR_HOSTNAME}}/"
        icon: "sh-cadvisor.png"
        server: "my-docker"
        showStats: true
    - Dozzle:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-dozzle-1"
        description: "Simple Container Monitoring and Logging"
        href: "https://{{HOMEPAGE_VAR_DOZZLE_HOSTNAME}}/"
        icon: "sh-dozzle.png"
        server: "my-docker"
        showStats: true
    - Grafana:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-grafana-1"
        description: "The open and composable observability and data visualization platform"
        href: "https://{{HOMEPAGE_VAR_GRAFANA_HOSTNAME}}/"
        icon: "sh-grafana.png"
        server: "my-docker"
        showStats: true
        widget:
          type: "grafana"
          url: "http://grafana:{{HOMEPAGE_VAR_GRAFANA_PORT}}"
          username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
    - Grafana Alloy:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-grafana-alloy-1"
        description: "Grafana Alloy is an open source OpenTelemetry collector with built-in Prometheus pipelines and support for metrics, logs, traces, and profiles"
        href: "https://{{HOMEPAGE_VAR_GRAFANA_ALLOY_HOSTNAME}}/"
        icon: "sh-grafana-alloy.png"
        server: "my-docker"
        showStats: true
    - IT TOOLS:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-it-tools-1"
        description: "Handy tools for developers"
        href: "https://{{HOMEPAGE_VAR_IT_TOOLS_HOSTNAME}}/"
        icon: "sh-it-tools.png"
        server: "my-docker"
        showStats: true
    - Mailpit:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-mailpit-1"
        description: "Mailpit - email & SMTP testing tool with API for developers"
        href: "https://{{HOMEPAGE_VAR_MAILPIT_HOSTNAME}}/"
        icon: "sh-mailpit.png"
        server: "my-docker"
        showStats: true
        widget:
          mappings:
            - field: "total"
              label: "Total"
            - field: "unread"
              label: "Unread"
          type: "customapi"
          url: "http://mailpit:{{HOMEPAGE_VAR_MAILPIT_PORT}}/api/v1/messages"
    - Mealie:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-mealie-1"
        description: "Mealie is an intuitive and easy to use recipe management app"
        href: "https://{{HOMEPAGE_VAR_MEALIE_HOSTNAME}}/"
        icon: "sh-mealie.png"
        server: "my-docker"
        showStats: true
        widget:
          type: "mealie"
          key: "{{HOMEPAGE_VAR_MEALIE_TOKEN}}"
          url: "http://mealie:{{HOMEPAGE_VAR_MEALIE_PORT}}"
          version: 2
    - Mongo Express:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-mongo-mongo-express-1"
        description: "A web-based MongoDB admin interface written with Node.js, Express, and Bootstrap 5"
        href: "https://{{HOMEPAGE_VAR_MONGO_EXPRESS_HOSTNAME}}/"
        icon: "/icons/mongo-express.png"
        server: "my-docker"
        showStats: true
    - n8n:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-n8n-1"
        description: "Fair-code workflow automation platform with native AI capabilities"
        href: "https://{{HOMEPAGE_VAR_N8N_HOSTNAME}}/"
        icon: "sh-n8n.png"
        server: "my-docker"
        showStats: true
    - ntfy:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-ntfy-1"
        description: "ntfy (pronounced notify) is a simple HTTP-based pub-sub notification service. It allows you to send notifications to your phone or desktop via scripts from any computer, and/or using a REST API"
        href: "https://{{HOMEPAGE_VAR_NTFY_HOSTNAME}}/"
        icon: "sh-ntfy.png"
        server: "my-docker"
        showStats: true
    - Omni Tools:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-omni-tools-1"
        description: "Self-hosted collection of powerful web-based tools for everyday tasks"
        href: "https://{{HOMEPAGE_VAR_OMNI_TOOLS_HOSTNAME}}/"
        icon: "sh-omnitools.png"
        server: "my-docker"
        showStats: true
    - pgAdmin4:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-postgres-pgadmin4-1"
        description: "pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL"
        href: "https://{{HOMEPAGE_VAR_PGADMIN4_HOSTNAME}}/"
        icon: "/icons/pgadmin4.ico"
        server: "my-docker"
        showStats: true
    - phpMyAdmin:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-mysql-phpmyadmin-1"
        description: "phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web"
        href: "https://{{HOMEPAGE_VAR_PHPMYADMIN_HOSTNAME}}/"
        icon: "/icons/phpmyadmin.ico"
        server: "my-docker"
        showStats: true
    - Prometheus:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-prometheus-1"
        description: "Monitor your applications, systems, and services with the leading open source monitoring solution. Instrument, collect, store, and query your metrics for alerting, dashboarding, and other use cases"
        href: "https://{{HOMEPAGE_VAR_PROMETHEUS_HOSTNAME}}/"
        icon: "sh-prometheus.png"
        server: "my-docker"
        showStats: true
        widget:
          type: "prometheus"
          url: "http://prometheus:{{HOMEPAGE_VAR_PROMETHEUS_PORT}}"
    - Open WebUI:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-ollama-open-webui-1"
        description: "Open WebUI is an extensible, self-hosted AI interface that adapts to your workflow, all while operating entirely offline"
        href: "https://{{HOMEPAGE_VAR_OPEN_WEBUI_HOSTNAME}}/"
        icon: "sh-open-webui.png"
        server: "my-docker"
        showStats: true
    - RabbitMQ:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-rabbitmq-1"
        description: "RabbitMQ is a reliable and mature messaging and streaming broker, which is easy to deploy on cloud environments, on-premises, and on your local machine"
        href: "https://{{HOMEPAGE_VAR_RABBITMQ_HOSTNAME}}/"
        icon: "sh-rabbitmq.png"
        server: "my-docker"
        showStats: true
    - Redis Insight:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-redis-redisinsight-1"
        description: "Redis Insight is a powerful tool for visualizing and optimizing data in Redis or Redis Stack, making real-time application development easier and more fun than ever before"
        href: "https://{{HOMEPAGE_VAR_REDIS_HOSTNAME}}/"
        icon: "/icons/redisinsight.png"
        server: "my-docker"
        showStats: true
    - seaweedFS:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-seaweedfs-1"
        description: "Enterprise-Grade Distributed Storage with Self-Healing"
        href: "https://{{HOMEPAGE_VAR_SEAWEEDFS_HOSTNAME}}/"
        icon: "sh-seaweedfs.png"
        server: "my-docker"
        showStats: true
    - Traefik:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-traefik-1"
        description: "Traefik is a leading modern open source reverse proxy and ingress controller that makes deploying services and APIs easy"
        href: "https://{{HOMEPAGE_VAR_TRAEFIK_HOSTNAME}}/"
        icon: "sh-traefik.png"
        server: "my-docker"
        showStats: true
        widget:
          type: "traefik"
          url: "http://traefik:{{HOMEPAGE_VAR_TRAEFIK_PORT}}"
    - What's up Docker?:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-whatsupdocker-1"
        description: "Keep your containers up-to-date!"
        href: "https://{{HOMEPAGE_VAR_WHATSUPDOCKER_HOSTNAME}}/"
        icon: "/icons/wud.svg"
        server: "my-docker"
        showStats: true
        widget:
          type: "whatsupdocker"
          url: "http://whatsupdocker:{{HOMEPAGE_VAR_WHATSUPDOCKER_PORT}}"
    - whoami:
        container: "{{HOMEPAGE_VAR_COMPOSE_PROJECT_NAME}}-traefik-whoami-1"
        description: "Tiny Go webserver that prints OS information and HTTP request to output"
        href: "https://{{HOMEPAGE_VAR_WHOAMI_HOSTNAME}}/"
        icon: "/icons/whoami.png"
        server: "my-docker"
        showStats: true
