background:
  blur: "md"
  brightness: 75
  image: "/images/background.png"
  opacity: 25
layout:
  Bookmarks:
    columns: 3
    style: "row"
  Services:
    columns: 3
    style: "row"
  Misc:
    columns: 3
    style: "row"
quicklaunch:
  searchDescriptions: true
title: "Docker dashboard"
