# https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-data-source
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://grafana-loki:3100
    isDefault: false
    editable: false
