services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_OPEN_WEBUI_GPU_DRIVER-nvidia}
              count: ${OLLAMA_OPEN_WEBUI_GPU_COUNT-1}
              capabilities:
                - gpu
