services:
  ollama:
    deploy:
      resources:
        limits:
          memory: "2G"
        reservations:
          devices:
            - driver: "nvidia"
              count: ${OLLAMA_OPEN_WEBUI_GPU_COUNT-1}
              capabilities:
                - gpu
