networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  ollama:
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "timeout 1 bash -c '</dev/tcp/localhost/11434' || exit 1"
      timeout: "10s"
    image: "ollama/ollama:${OLLAMA_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+-rocm$$"
      wud.watch: true
    networks:
      - "default"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "ollama-data:/root/.ollama"
  ollama-open-webui:
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      ENABLE_SIGNUP: false
      OLLAMA_BASE_URL: "http://ollama:11434"
      WEBUI_AUTH: false
      WEBUI_SECRET_KEY: "${OLLAMA_OPEN_WEBUI_WEBUI_SECRET_KEY:?err}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "ghcr.io/open-webui/open-webui:${OLLAMA_OPEN_WEBUI_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.ollama-open-webui.entrypoints: "websecure"
      traefik.http.routers.ollama-open-webui.middlewares: "authentik-server@docker"
      traefik.http.routers.ollama-open-webui.rule: "Host(`${OLLAMA_OPEN_WEBUI_HOSTNAME:?err}`)"
      traefik.http.routers.ollama-open-webui.tls: true
      traefik.http.services.ollama-open-webui.loadbalancer.server.port: "${OLLAMA_OPEN_WEBUI_HOSTNAME_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "default"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "ollama-open-webui-data:/app/backend/data"
volumes:
  ollama-data: null
  ollama-open-webui-data: null
