networks:
  authentik:
    external: true
    name: "${AUTHENTIK_NETWORK:?err}"
  mailpit:
    external: true
    name: "${MAILPIT_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  homepage:
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "${HOMEPAGE_HOSTNAME}"
      HOMEPAGE_VAR_AUTHENTIK_HOSTNAME: "${AUTHENTIK_HOSTNAME}"
      HOMEPAGE_VAR_AUTHENTIK_PORT: "${AUTHENTIK_HOSTNAME_PORT}"
      HOMEPAGE_VAR_AUTHENTIK_TOKEN: "${AUTHENTIK_BOOTSTRAP_TOKEN}"
      HOMEPAGE_VAR_CADVISOR_HOSTNAME: "${CADVISOR_HOSTNAME}"
      HOMEPAGE_VAR_COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      HOMEPAGE_VAR_DOZZLE_HOSTNAME: "${DOZZLE_HOSTNAME}"
      HOMEPAGE_VAR_GOTIFY_HOSTNAME: "${GOTIFY_HOSTNAME}"
      HOMEPAGE_VAR_GOTIFY_PORT: "${GOTIFY_HOSTNAME_PORT}"
      HOMEPAGE_VAR_GOTIFY_TOKEN: "${HOMEPAGE_GOTIFY_TOKEN}"
      HOMEPAGE_VAR_GRAFANA_ALLOY_HOSTNAME: "${GRAFANA_ALLOY_HOSTNAME}"
      HOMEPAGE_VAR_GRAFANA_HOSTNAME: "${GRAFANA_HOSTNAME}"
      HOMEPAGE_VAR_GRAFANA_PASSWORD: "${GRAFANA_GF_SECURITY_ADMIN_PASSWORD}"
      HOMEPAGE_VAR_GRAFANA_PORT: "${GRAFANA_HOSTNAME_PORT}"
      HOMEPAGE_VAR_GRAFANA_USER: "${GRAFANA_GF_SECURITY_ADMIN_USER}"
      HOMEPAGE_VAR_IT_TOOLS_HOSTNAME: "${IT_TOOLS_HOSTNAME}"
      HOMEPAGE_VAR_MAILPIT_HOSTNAME: "${MAILPIT_HOSTNAME}"
      HOMEPAGE_VAR_MAILPIT_PORT: "${MAILPIT_HOSTNAME_PORT}"
      HOMEPAGE_VAR_MEALIE_HOSTNAME: "${MEALIE_HOSTNAME}"
      HOMEPAGE_VAR_MEALIE_PORT: "${MEALIE_HOSTNAME_PORT}"
      HOMEPAGE_VAR_MEALIE_TOKEN: "${HOMEPAGE_MEALIE_TOKEN}"
      HOMEPAGE_VAR_MINIO_HOSTNAME: "${MINIO_HOSTNAME}"
      HOMEPAGE_VAR_MONGO_EXPRESS_HOSTNAME: "${MONGO_EXPRESS_HOSTNAME}"
      HOMEPAGE_VAR_N8N_HOSTNAME: "${N8N_HOSTNAME}"
      HOMEPAGE_VAR_OMNI_TOOLS_HOSTNAME: "${OMNI_TOOLS_HOSTNAME}"
      HOMEPAGE_VAR_OPEN_WEBUI_HOSTNAME: "${OLLAMA_OPEN_WEBUI_HOSTNAME}"
      HOMEPAGE_VAR_PGADMIN4_HOSTNAME: "${POSTGRES_PGADMIN4_HOSTNAME}"
      HOMEPAGE_VAR_PHPMYADMIN_HOSTNAME: "${MYSQL_PHPMYADMIN_HOSTNAME}"
      HOMEPAGE_VAR_PROMETHEUS_HOSTNAME: "${PROMETHEUS_HOSTNAME}"
      HOMEPAGE_VAR_PROMETHEUS_PORT: "${PROMETHEUS_HOSTNAME_PORT}"
      HOMEPAGE_VAR_RABBITMQ_HOSTNAME: "${RABBITMQ_HOSTNAME}"
      HOMEPAGE_VAR_REDIS_HOSTNAME: "${REDIS_HOSTNAME}"
      HOMEPAGE_VAR_TRAEFIK_HOSTNAME: "${TRAEFIK_HOSTNAME}"
      HOMEPAGE_VAR_TRAEFIK_PORT: "${TRAEFIK_HOSTNAME_PORT}"
      HOMEPAGE_VAR_WHATSUPDOCKER_HOSTNAME: "${WHATSUPDOCKER_HOSTNAME}"
      HOMEPAGE_VAR_WHATSUPDOCKER_PORT: "${WHATSUPDOCKER_HOSTNAME_PORT}"
      HOMEPAGE_VAR_WHOAMI_HOSTNAME: "${TRAEFIK_WHOAMI_HOSTNAME}"
    image: "ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: "websecure"
      traefik.http.routers.homepage.middlewares: "authentik-server@docker"
      traefik.http.routers.homepage.rule: "Host(`${HOMEPAGE_HOSTNAME:?err}`)"
      traefik.http.routers.homepage.tls: true
      traefik.http.services.homepage.loadbalancer.server.port: "${HOMEPAGE_HOSTNAME_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "authentik"
      - "mailpit"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "${PWD}/services/homepage/config/bookmarks.yaml:/app/config/bookmarks.yaml:ro"
      - "${PWD}/services/homepage/config/docker.yaml:/app/config/docker.yaml:ro"
      - "${PWD}/services/homepage/config/services.yaml:/app/config/services.yaml:ro"
      - "${PWD}/services/homepage/config/settings.yaml:/app/config/settings.yaml:ro"
      - "${PWD}/services/homepage/config/widgets.yaml:/app/config/widgets.yaml:ro"
      - "${PWD}/services/homepage/public/icons:/app/public/icons:ro"
      - "${PWD}/services/homepage/public/images:/app/public/images:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "homepage-data:/app/config"
volumes:
  homepage-data: null
