networks:
  mailpit:
    external: true
    name: "${MAILPIT_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  homepage:
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "${HOMEPAGE_HOSTNAME}"
    image: "ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: "websecure"
      traefik.http.routers.homepage.middlewares: "authentik-server@docker"
      traefik.http.routers.homepage.rule: "Host(`${HOMEPAGE_HOSTNAME:?err}`)"
      traefik.http.routers.homepage.tls: true
      traefik.http.services.homepage.loadbalancer.server.port: "${HOMEPAGE_HOSTNAME_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mailpit"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "${PWD}/services/homepage/config/bookmarks.yaml:/app/config/bookmarks.yaml:ro"
      - "${PWD}/services/homepage/config/docker.yaml:/app/config/docker.yaml:ro"
      - "${PWD}/services/homepage/config/services.yaml:/app/config/services.yaml:ro"
      - "${PWD}/services/homepage/config/settings.yaml:/app/config/settings.yaml:ro"
      - "${PWD}/services/homepage/config/widgets.yaml:/app/config/widgets.yaml:ro"
      - "${PWD}/services/homepage/public/icons:/app/public/icons:ro"
      - "${PWD}/services/homepage/public/images:/app/public/images:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "homepage-data:/app/config"
volumes:
  homepage-data: null
