networks:
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
  redis:
    external: true
    name: "${REDIS_NETWORK:?err}"
services:
  redis:
    command: "redis-server --appendonly yes --save 60 1 --requirepass ${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "redis-cli --pass ${REDIS_PASSWORD} ping | grep PONG || exit 1"
      timeout: "10s"
    image: "redis:${REDIS_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+-alpine$$"
      wud.watch: true
    networks:
      - "redis"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "redis-data:/data"
  redis-prometheus-exporter:
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD:?err}"
      REDIS_USER: null
    image: "oliver006/redis_exporter:${REDIS_EXPORTER_VERSION:?err}"
    labels:
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+-alpine$$"
      wud.watch: true
    networks:
      - "prometheus"
      - "redis"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
  redis-redisinsight:
    environment:
      VIRTUAL_HOST: "${REDIS_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${REDIS_VIRTUAL_PORT:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://localhost:5540/api/health || exit 1"
      timeout: "10s"
    image: "redis/redisinsight:${REDIS_REDISINSIGHT_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.redis-redisinsight.entrypoints: "websecure"
      traefik.http.routers.redis-redisinsight.middlewares: "authentik-server@docker"
      traefik.http.routers.redis-redisinsight.rule: "Host(`${REDIS_VIRTUAL_HOST:?err}`)"
      traefik.http.routers.redis-redisinsight.tls: true
      traefik.http.services.redis-redisinsight.loadbalancer.server.port: "${REDIS_VIRTUAL_PORT:?err}"
      wud.tag.include: "^\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "proxy"
      - "redis"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "redis-redisinsight-data:/data"
volumes:
  redis-data: null
  redis-redisinsight-data: null
