name: authentik
description: "authentik is an IdP (Identity Provider) and SSO (Single Sign On) platform that is built with security at the forefront of every piece of code, every feature, with an emphasis on flexibility and versatility"
url: "https://goauthentik.io/"
local_url: "https://authentik.services.local"
docker_hub_url: "https://github.com/goauthentik/authentik/pkgs/container/server"
dockerfile_url: "https://github.com/goauthentik/authentik/blob/main/lifecycle/container/Dockerfile"
