networks:
  bitwarden:
    external: true
    name: "${BITWARDEN_NETWORK:?err}"
  nginx-proxy:
    external: true
    name: "${NGINX_PROXY_NETWORK:?err}"
services:
  bitwarden:
    depends_on:
      - "bitwarden-postgres"
    environment:
      BW_DB_DATABASE: "${BITWARDEN_POSTGRES_DB:?err}"
      BW_DB_PASSWORD: "${BITWARDEN_POSTGRES_PASSWORD:?err}"
      BW_DB_PROVIDER: "postgres"
      BW_DB_SERVER: "bitwarden-postgres"
      BW_DB_USERNAME: "${BITWARDEN_POSTGRES_USER:?err}"
      BW_DOMAIN: "${BITWARDEN_VIRTUAL_HOST:?err}"
      BW_INSTALLATION_ID: "${BITWARDEN_BW_INSTALLATION_ID:?err}"
      BW_INSTALLATION_KEY: "${BITWARDEN_BW_INSTALLATION_KEY:?err}"
      TZ: "${TZ:?err}"
      VIRTUAL_HOST: "${BITWARDEN_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${BITWARDEN_VIRTUAL_PORT:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test: "curl -f http://localhost:8080/alive || exit 1"
      timeout: "10s"
    image: "ghcr.io/bitwarden/self-host:${BITWARDEN_VERSION:?err}"
    labels:
      wud.tag.include: "latest"
      wud.watch.digest: true
    networks:
      - "bitwarden"
      - "nginx-proxy"
    restart: "unless-stopped"
    volumes:
      - "bitwarden-data:/etc/bitwarden"
      - "bitwarden-logs:/var/log/bitwarden"
  bitwarden-postgres:
    environment:
      POSTGRES_DB: "${BITWARDEN_POSTGRES_DB:?err}"
      POSTGRES_PASSWORD: "${BITWARDEN_POSTGRES_PASSWORD:?err}"
      POSTGRES_USER: "${BITWARDEN_POSTGRES_USER:?err}"
      TZ: "${TZ:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      timeout: "10s"
    image: "postgres:${BITWARDEN_POSTGRES_VERSION:?err}"
    labels:
      wud.tag.include: "^\\d+\\.\\d+$$"
    networks:
      - "bitwarden"
    restart: "unless-stopped"
    volumes:
      - "bitwarden-postgres-data:/var/lib/postgresql/data"
volumes:
  bitwarden-data: null
  bitwarden-logs: null
  bitwarden-postgres-data: null
