networks:
  mailpit:
    external: true
    name: "${MAILPIT_NETWORK:?err}"
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  mailpit:
    environment:
      MP_ENABLE_PROMETHEUS: true
    image: "axllent/mailpit:${MAILPIT_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.mailpit.entrypoints: "websecure"
      traefik.http.routers.mailpit.middlewares: "authentik-server@docker"
      traefik.http.routers.mailpit.rule: "Host(`${MAILPIT_HOST:?err}`)"
      traefik.http.routers.mailpit.tls: true
      traefik.http.services.mailpit.loadbalancer.server.port: "${MAILPIT_HOST_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mailpit"
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "mailpit-data:/data"
volumes:
  mailpit-data: null
