networks:
  mailpit:
    external: true
    name: "${MAILPIT_NETWORK:?err}"
  prometheus:
    external: true
    name: "${PROMETHEUS_NETWORK:?err}"
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  mailpit:
    environment:
      MP_ENABLE_PROMETHEUS: true
      VIRTUAL_HOST: "${MAILPIT_VIRTUAL_HOST:?err}"
      VIRTUAL_PORT: "${MAILPIT_VIRTUAL_PORT:?err}"
    healthcheck:
      interval: "30s"
      retries: 5
      start_period: "60s"
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://localhost:8025/api/v1/info || exit 1"
      timeout: "10s"
    image: "axllent/mailpit:${MAILPIT_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.mailpit.entrypoints: "websecure"
      traefik.http.routers.mailpit.middlewares: "authentik-server@docker"
      traefik.http.routers.mailpit.rule: "Host(`${MAILPIT_VIRTUAL_HOST:?err}`)"
      traefik.http.routers.mailpit.tls: true
      traefik.http.services.mailpit.loadbalancer.server.port: "${MAILPIT_VIRTUAL_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "mailpit"
      - "prometheus"
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "mailpit-data:/data"
volumes:
  mailpit-data: null
