networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:?err}"
services:
  mealie:
    deploy:
      resources:
        limits:
          memory: "1000M"
    environment:
      ALLOW_PASSWORD_LOGIN: true
      BASE_URL: "https://${MEALIE_HOSTNAME:?err}:${MEALIE_HOSTNAME_PORT:?err}"
    image: "ghcr.io/mealie-recipes/mealie:${MEALIE_VERSION:?err}"
    labels:
      traefik.docker.network: "${PROXY_NETWORK:?err}"
      traefik.enable: true
      traefik.http.routers.mealie.entrypoints: "websecure"
      traefik.http.routers.mealie.rule: "Host(`${MEALIE_HOSTNAME:?err}`)"
      traefik.http.routers.mealie.tls: true
      traefik.http.services.mealie.loadbalancer.server.port: "${MEALIE_HOSTNAME_PORT:?err}"
      wud.tag.include: "^v\\d+\\.\\d+\\.\\d+$$"
      wud.watch: true
    networks:
      - "proxy"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "mealie-data:/app/data"
volumes:
  mealie-data: null
