#!/bin/bash
set -e

export PGPASSWORD="${POSTGRES_USER_PASSWORD}"

psql -U "${POSTGRES_USER}" -d "postgres" <<-EOT
CREATE USER ${POSTGRES_EXPORTER_USER} WITH PASSWORD '${POSTGRES_EXPORTER_USER_PASSWORD}';
GRANT pg_monitor TO ${POSTGRES_EXPORTER_USER};
EOT

unset PGPASSWORD
