#!/bin/bash
set -eu

export PGPASSWORD="${POSTGRES_PASSWORD}"

psql -U "${POSTGRES_USER}" -d "postgres" <<-EOSQL
CREATE USER ${POSTGRES_EXPORTER_USER} WITH PASSWORD '${POSTGRES_EXPORTER_USER_PASSWORD}';
GRANT pg_monitor TO ${POSTGRES_EXPORTER_USER};
EOSQL

unset PGPASSWORD
